import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ToastContainer } from 'react-toastify';

import React from 'react';
import { AuthProvider } from '@/context/AuthContext';

const haskoy = localFont({
  src: './fonts/Haskoy[wght].woff2',
  variable: '--font-haskoy',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${haskoy.variable} antialiased`}>
          <AuthProvider>
            {children}
            <ToastContainer />
          </AuthProvider>
      </body>
    </html>
  );
}
